version: '3.4'

services:
    UpcomingEventsReport:
        image: deofex/nftbotv3:upcomingeventsreport
        env_file:
            - prod.env
    DailyReport:
        image: deofex/nftbotv3:dailyreport
        env_file:
            - prod.env
