version: '3.4'

services:
    UpcomingEventsReport:
        image: deofex/nftbotv3:upcomingeventsreport
        build:
            context: .
            dockerfile: ./UpcomingEventsReport/Dockerfile
        env_file:
            - dev.env
    DailyReport:
        image: deofex/nftbotv3:dailyreport
        build:
            context: .
            dockerfile: ./DailyReport/Dockerfile
        env_file:
            - dev.env
